---
name: now8
description: Improved public transport arrival time estimations using Machine Learning.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  recase: ^4.0.0
  provider: ^6.0.1
  http: ^0.13.4
  intl: ^0.17.0
  flutter_cache_manager: ^3.2.0
  dropdown_search: ^2.0.1
  fuzzy: ^0.4.0-nullsafety.0
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  test: ^1.19.4
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
