---
on:
  push:

jobs:
  main:
    name: Main workflow
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - name: Setup Flutter stable
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install dependencies
        run: make install

      - name: Disable pre-commit
        run: pre-commit uninstall

      - name: Check lint
        run: SKIP=no-commit-to-branch make lint

      - name: Run tests
        run: make test

      # Create release if in main branch
      - name: Build
        if: github.ref == 'refs/heads/main'
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: echo $KEY_JKS > key.jks && make build

      - name: commitizen
        if: github.ref == 'refs/heads/main'
        uses: commitizen-tools/commitizen-action@0.10.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          branch: main


      - name: Create GitHub release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/*
            build/app/outputs/bundle/release/app-release.aab
          body_path: body.md
          tag_name: ${{ env.REVISION }}

      # Deploy web
      - name: Install SSH Key
        if: github.ref == 'refs/heads/main'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy with rsync
        if: github.ref == 'refs/heads/main'
        run: |-
          rsync -Pavh --delete \
          ./build/web/ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}}:/var/www/now8/

      # Deploy docs
      - name: Build docs
        if: github.ref == 'refs/heads/main'
        run: make docs

      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/api
