---
on:
  push:
    tags:
      - '*'
jobs:
  releases:
    name: Release apk
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Setup Flutter stable
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze the code
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Build apk
        run: flutter build apk
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/debug/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
