---
on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - name: Setup Flutter stable
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze the code
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Clone repo
        uses: actions/checkout@v2
        if: github.ref == 'refs/heads/main'
      - name: commitizen
        uses: commitizen-tools/commitizen-action@0.10.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          branch: main
      - name: Build apk
        if: github.ref == 'refs/heads/main'
        run: flutter build apk
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: build/app/outputs/apk/app-release.apk
          body_path: body.md
          tag_name: ${{ env.REVISION }}
